### PR TITLE
Added .templateMarker

### PR DESCRIPTION
**Pull request by KOLANICH**
Proposal: to use the file with this name to track usage of the template and maybe distribute updates to the repos using it via a special bot in future.

While GH has a feature to mark a repo as a template, it has drawbacks that
* there is no way to get all the repos using the template;
* it is not possible to mark an existing repo as the one using the template without deletion of the repo (this way nuking all the issues, disconnecting it from fork network, and having all the stars disappeared). So marking an existing repo this way is completely useless.

Creating a file with a special name solves such issues.
* though I haven't figured out how to search by a file with such an extension (it seems GH lacks such a feature currently, though it has a feature of searching by a programming language, I wonder if such a file can be declared an own programming language), surely search results can be filtered client-side;
* adding and removing of a file can be done without repo recreation.

Also:
* it is not locked to GitHub, so this kind of searches can be done on other platforms too.

### CODE REVIEW

**Comment by jaraco** [comment]
This repo already has a marker (`skeleton.md`), so I'm a little reluctant to add another marker. I would be happy for the marker to be smaller and maybe just reference the template repo.

Another thing to consider as you're exploring this approach is that you can detect projects that use this template (or at least did at one point) will have one of the root commits in their history (i.e. 5ad18328e8f38abcc5a0fc4a549e7a3c40697d4e or c681f6748acaea1bf0b706528c36327cc94a6eed). And of course, you could use other commits too, but that would only reveal projects that had that more selective commit. If github had a way to search projects for a commit hash, that would reliably show projects using it. And it [appears it does](https://github.com/search?q=c681f6748acaea1bf0b706528c36327cc94a6eed&type=commits). Does that satisfy the need you have?

By the way, thanks for raising this concern. I'm pleased to see how easy it is to find skeleton-based projects.

**Comment by KOLANICH** [comment]
>This repo already has a marker (skeleton.md), so I'm a little reluctant to add another marker.

Thanks for notifying me about it. I have paid completely no attention to that file (how about a badge to make it more visible? `🦴` (yes, it will look different on different machines, but it is by design) in the left, `skeletoned` grey text on black background in the right.), so had some misassumptions about how it is used.

>Another thing to consider as you're exploring this approach is that you can detect projects that use this template (or at least did at one point) will have one of the root commits in their history (i.e. 5ad1832 or c681f67). And of course, you could use other commits too, but that would only reveal projects that had that more selective commit. If github had a way to search projects for a commit hash, that would reliably show projects using it. And it appears it does. Does that satisfy the need you have?

I had misassumptions that it is used the same way I use an own but a similar template (in fact most of the PR's I have sent here basically add the things I have in my one). I use my template without preserving commits hashes (the initial commit is rewritten to be a real initial commit, not empty boilerplate) and don't rely on VCS for merging, so commit hash would likely be not very useful. The drawback with using VCS is that history gets bloated. BTW, you may want to look at https://github.com/open-source-ideas/open-source-ideas/issues/262 .

**Comment by jaraco** [comment]
> how about a badge to make it more visible?

For sure! I had the same idea. Care to make one and add it to the README?

> The drawback with using VCS is that history gets bloated.

Indeed, but I find that tradeoff to be small in favor of the VCS, because it tracks the actual changes you're applying to a project, and the bloat can be mitigated somewhat by rare roll-up commits.

> BTW, you may want to look at [open-source-ideas/open-source-ideas#262](https://github.com/open-source-ideas/open-source-ideas/issues/262) .

Will do.

**Comment by KOLANICH** [comment]
>Care to make one and add it to the README?

Sorry, I currently have no plans for that.

**Pull request closed without merging**
