### PR TITLE
Removed setup.py, since setuptools now supports workflows with setup.cfg only

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by KOLANICH** [comment]
About errors related to editable installs: https://github.com/pypa/pip/pull/9547

**Comment by jaraco** [comment]
Ping me on this when it's viable. I'm interested in making it happen.

**Comment by KOLANICH** [comment]
@jaraco, the PR into pip is merged.

**Comment by jaraco** [comment]
Sounds good. We'll need some time for pip to cut a release and then have to decide whether to require that release or to wait until that release is generally available. This issue will primarily affect development workflows.

**Pull request closed without merging**
